24-01-2025 21:08:56 - Cloud-cache-clean - ERROR - Error in index2(): 'name_servers'
24-01-2025 21:08:56 - Cloud-cache-clean - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.11/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/flask/app.py", line 1212, in make_response
    raise TypeError(
TypeError: The view function for 'index' did not return a valid response. The function either returned None or ended without a return statement.
24-01-2025 21:11:27 - Cloud-cache-clean - ERROR - Error in index2(): 'name_servers'
24-01-2025 21:11:27 - Cloud-cache-clean - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.11/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/flask/app.py", line 1212, in make_response
    raise TypeError(
TypeError: The view function for 'index' did not return a valid response. The function either returned None or ended without a return statement.
24-01-2025 21:22:36 - Cloud-cache-clean - ERROR - Error in index2(): cannot access local variable 'nameserver1' where it is not associated with a value
24-01-2025 21:22:36 - Cloud-cache-clean - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.11/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/flask/app.py", line 1212, in make_response
    raise TypeError(
TypeError: The view function for 'index' did not return a valid response. The function either returned None or ended without a return statement.
24-01-2025 21:23:11 - Cloud-cache-clean - ERROR - Error in index2(): not enough values to unpack (expected 2, got 0)
24-01-2025 21:23:11 - Cloud-cache-clean - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.11/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/flask/app.py", line 1212, in make_response
    raise TypeError(
TypeError: The view function for 'index' did not return a valid response. The function either returned None or ended without a return statement.
